'use client';

import { useState, useEffect, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  DollarSign,
  Users,
  TrendingUp,
  Calendar,
  Download,
  Plus,
  Search,
  RefreshCw,
  CheckCircle,
  XCircle,
  Clock,
} from 'lucide-react';
import { toast } from 'sonner';

interface Settlement {
  _id: string;
  settlementNumber: string;
  partnerName: string;
  partnerEmail: string;
  periodStart: string;
  periodEnd: string;
  totalOrders: number;
  totalOrderAmount: number;
  totalCommissionAmount: number;
  totalSettlementAmount: number;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  createdAt: string;
}

interface Stats {
  _id: string;
  count: number;
  totalAmount: number;
}

export default function AdminSettlementsPage() {
  const [settlements, setSettlements] = useState<Settlement[]>([]);
  const [stats, setStats] = useState<Stats[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [selectedSettlement, setSelectedSettlement] = useState<Settlement | null>(null);
  const [showDetailDialog, setShowDetailDialog] = useState(false);
  const [showStatusDialog, setShowStatusDialog] = useState(false);
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  const [newStatus, setNewStatus] = useState('');
  const [statusReason, setStatusReason] = useState('');

  useEffect(() => {
    fetchSettlements();
  }, [page, statusFilter]);

  const fetchSettlements = async () => {
    try {
      setLoading(true);
      const params = new URLSearchParams({
        page: page.toString(),
        limit: '10',
        ...(statusFilter && { status: statusFilter }),
        ...(search && { search }),
      });

      const response = await fetch(`/api/admin/settlements?${params}`);
      const data = await response.json();

      if (data.success) {
        setSettlements(data.data.settlements);
        setTotal(data.data.pagination.total);
        setStats(data.data.stats);
      }
    } catch (error) {
      console.error('Error fetching settlements:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = () => {
    setPage(1);
    fetchSettlements();
  };

  const handleStatusChange = async () => {
    if (!selectedSettlement || !newStatus) return;

    try {
      const response = await fetch(`/api/admin/settlements/${selectedSettlement._id}/status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: newStatus, reason: statusReason }),
      });

      const data = await response.json();
      if (data.success) {
        toast.success('정산 상태가 변경되었습니다.');
        setShowStatusDialog(false);
        setNewStatus('');
        setStatusReason('');
        fetchSettlements();
      } else {
        toast.error(data.error?.message || '상태 변경에 실패했습니다.');
      }
    } catch (error) {
      console.error('Error updating status:', error);
      toast.error('상태 변경 중 오류가 발생했습니다.');
    }
  };

  const handleAutoGenerate = async () => {
    try {
      const now = new Date();
      const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);

      const response = await fetch('/api/admin/settlements/auto-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          year: lastMonth.getFullYear(),
          month: lastMonth.getMonth() + 1,
          minAmount: 10000,
        }),
      });

      const data = await response.json();
      if (data.success) {
        toast.success(`${data.data.summary.success}개의 정산이 생성되었습니다.`);
        setShowAutoGenerateDialog(false);
        fetchSettlements();
      } else {
        toast.error(data.error?.message || '자동 정산 생성에 실패했습니다.');
      }
    } catch (error) {
      console.error('Error auto-generating settlements:', error);
      toast.error('자동 정산 생성 중 오류가 발생했습니다.');
    }
  };

  const getStatusBadge = (status: string) => {
    const variants: Record<string, { variant: any; label: string; icon: any }> = {
      pending: { variant: 'secondary', label: '대기', icon: Clock },
      processing: { variant: 'default', label: '처리중', icon: RefreshCw },
      completed: { variant: 'default', label: '완료', icon: CheckCircle },
      failed: { variant: 'destructive', label: '실패', icon: XCircle },
      cancelled: { variant: 'outline', label: '취소', icon: XCircle },
    };

    const config = variants[status] || variants.pending;
    const Icon = config.icon;

    return (
      <Badge variant={config.variant as any} className="flex items-center gap-1">
        <Icon className="w-3 h-3" />
        {config.label}
      </Badge>
    );
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('ko-KR', {
      style: 'currency',
      currency: 'KRW',
    }).format(amount);
  };

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString('ko-KR');
  };

  // 통계 카드 계산
  const totalPending = stats.find(s => s._id === 'pending')?.totalAmount || 0;
  const totalCompleted = stats.find(s => s._id === 'completed')?.totalAmount || 0;
  const pendingCount = stats.find(s => s._id === 'pending')?.count || 0;

  return (
    <div className="p-6 space-y-6">
      {/* 헤더 */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold">정산 관리</h1>
          <p className="text-gray-500 mt-1">파트너 정산 내역을 관리합니다</p>
        </div>
        <div className="flex gap-2">
          <Button onClick={() => setShowAutoGenerateDialog(true)} variant="outline">
            <Plus className="w-4 h-4 mr-2" />
            자동 정산 생성
          </Button>
          <Button onClick={() => fetchSettlements()} variant="outline">
            <RefreshCw className="w-4 h-4 mr-2" />
            새로고침
          </Button>
        </div>
      </div>

      {/* 통계 카드 */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">대기 중인 정산</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{pendingCount}건</div>
            <p className="text-xs text-muted-foreground">
              {formatCurrency(totalPending)}
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">완료된 정산</CardTitle>
            <CheckCircle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {stats.find(s => s._id === 'completed')?.count || 0}건
            </div>
            <p className="text-xs text-muted-foreground">
              {formatCurrency(totalCompleted)}
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">전체 정산 금액</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {formatCurrency(stats.reduce((sum, s) => sum + s.totalAmount, 0))}
            </div>
            <p className="text-xs text-muted-foreground">
              총 {stats.reduce((sum, s) => sum + s.count, 0)}건
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">평균 정산액</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {formatCurrency(
                stats.reduce((sum, s) => sum + s.totalAmount, 0) /
                  Math.max(stats.reduce((sum, s) => sum + s.count, 0), 1)
              )}
            </div>
            <p className="text-xs text-muted-foreground">건당 평균</p>
          </CardContent>
        </Card>
      </div>

      {/* 필터 및 검색 */}
      <Card>
        <CardHeader>
          <CardTitle>정산 목록</CardTitle>
          <CardDescription>파트너별 정산 내역을 조회하고 관리합니다</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-2 mb-4">
            <div className="flex-1">
              <Input
                placeholder="정산번호, 파트너명, 이메일 검색..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="상태 필터" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="">전체</SelectItem>
                <SelectItem value="pending">대기</SelectItem>
                <SelectItem value="processing">처리중</SelectItem>
                <SelectItem value="completed">완료</SelectItem>
                <SelectItem value="failed">실패</SelectItem>
                <SelectItem value="cancelled">취소</SelectItem>
              </SelectContent>
            </Select>
            <Button onClick={handleSearch}>
              <Search className="w-4 h-4 mr-2" />
              검색
            </Button>
          </div>

          {loading ? (
            <div className="text-center py-8">로딩 중...</div>
          ) : (
            <>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>정산번호</TableHead>
                    <TableHead>파트너</TableHead>
                    <TableHead>정산 기간</TableHead>
                    <TableHead className="text-right">주문 건수</TableHead>
                    <TableHead className="text-right">정산 금액</TableHead>
                    <TableHead>상태</TableHead>
                    <TableHead className="text-center">작업</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {settlements.map((settlement) => (
                    <TableRow key={settlement._id}>
                      <TableCell className="font-medium">
                        {settlement.settlementNumber}
                      </TableCell>
                      <TableCell>
                        <div>
                          <div className="font-medium">{settlement.partnerName}</div>
                          <div className="text-sm text-gray-500">{settlement.partnerEmail}</div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="text-sm">
                          {formatDate(settlement.periodStart)} ~<br />
                          {formatDate(settlement.periodEnd)}
                        </div>
                      </TableCell>
                      <TableCell className="text-right">{settlement.totalOrders}건</TableCell>
                      <TableCell className="text-right font-semibold">
                        {formatCurrency(settlement.totalSettlementAmount)}
                      </TableCell>
                      <TableCell>{getStatusBadge(settlement.status)}</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2 justify-center">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => {
                              setSelectedSettlement(settlement);
                              setShowDetailDialog(true);
                            }}
                          >
                            상세
                          </Button>
                          {settlement.status !== 'completed' && settlement.status !== 'cancelled' && (
                            <Button
                              size="sm"
                              onClick={() => {
                                setSelectedSettlement(settlement);
                                setShowStatusDialog(true);
                              }}
                            >
                              상태변경
                            </Button>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              {/* 페이지네이션 */}
              <div className="flex justify-center gap-2 mt-4">
                <Button
                  variant="outline"
                  onClick={() => setPage(p => Math.max(1, p - 1))}
                  disabled={page === 1}
                >
                  이전
                </Button>
                <span className="py-2 px-4">
                  {page} / {Math.ceil(total / 10)}
                </span>
                <Button
                  variant="outline"
                  onClick={() => setPage(p => p + 1)}
                  disabled={page >= Math.ceil(total / 10)}
                >
                  다음
                </Button>
              </div>
            </>
          )}
        </CardContent>
      </Card>

      {/* 상태 변경 다이얼로그 */}
      <Dialog open={showStatusDialog} onOpenChange={setShowStatusDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>정산 상태 변경</DialogTitle>
            <DialogDescription>
              {selectedSettlement?.settlementNumber}의 상태를 변경합니다
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>새로운 상태</Label>
              <Select value={newStatus} onValueChange={setNewStatus}>
                <SelectTrigger>
                  <SelectValue placeholder="상태 선택" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="processing">처리중</SelectItem>
                  <SelectItem value="completed">완료</SelectItem>
                  <SelectItem value="failed">실패</SelectItem>
                  <SelectItem value="cancelled">취소</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>사유 (선택)</Label>
              <Textarea
                value={statusReason}
                onChange={(e) => setStatusReason(e.target.value)}
                placeholder="상태 변경 사유를 입력하세요"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowStatusDialog(false)}>
              취소
            </Button>
            <Button onClick={handleStatusChange}>변경</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 자동 정산 생성 다이얼로그 */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>자동 정산 생성</DialogTitle>
            <DialogDescription>
              지난달 배송 완료된 주문을 기준으로 모든 파트너의 정산을 생성합니다.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <p className="text-sm text-gray-600">
              • 최소 정산 금액: 10,000원<br />
              • 배송 완료된 주문만 포함<br />
              • 이미 정산이 존재하는 경우 건너뜀
            </p>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAutoGenerateDialog(false)}>
              취소
            </Button>
            <Button onClick={handleAutoGenerate}>생성</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}



